from PySide6.QtCore import QObject


class Text(QObject):
    def __init__(self):
        super().__init__()
        self.AddNewProject = self.tr("添加新项目")
        self.Settings = self.tr("设置")
        self.Personalization = self.tr("个性化")
        self.ApplicationTheme = self.tr("应用主题")
        self.AAA = self.tr("调整应用的外观")
        self.Light = self.tr("浅色")
        self.Dark = self.tr("深色")
        self.FollowSystem = self.tr("跟随系统设置")
        self.ThemeColor = self.tr("主题色")
        self.AdjustThemeColor = self.tr("调整应用的主题颜色")
        self.SeafoamGreen = self.tr("海沫绿")
        self.InterfaceScaling = self.tr("界面缩放")
        self.ACAFS = self.tr("调整组件和字体的大小")
        self.Language = self.tr("语言")
        self.SetInterfaceLanguage = self.tr("设置界面语言")
        self.CloseDirectly = self.tr("直接关闭")
        self.EODDC = self.tr("启用或禁用直接关闭应用")
        self.DetectPrograms = self.tr("检测程序")
        self.ADAUPP = self.tr("自动检测并更新程序路径")
        self.About = self.tr("关于")
        self.CheckForUpdates = self.tr("检查更新")
        self.Copyleft = self.tr("Copyleft")
        self.CurrentVersion = self.tr("当前版本")
        self.SelectFile = self.tr("选择文件")
        self.Download = self.tr("下载")
        self.Detect = self.tr("检测")
        self.UpdateSuccessful = self.tr("更新成功")
        self.STEAR = self.tr("配置在重启软件后生效")