SOURCES += app/common/text.py

TRANSLATIONS += app/resource/i18n/app.en_US.ts \
    app/resource/i18n/app.ja_JP.ts \
    app/resource/i18n/app.ko_KR.ts \
    app/resource/i18n/app.zh_TW.ts \
    app/resource/i18n/app.fr_FR.ts \
    app/resource/i18n/app.de_DE.ts \
    app/resource/i18n/app.es_ES.ts \
    app/resource/i18n/app.pt_BR.ts \
    app/resource/i18n/app.ru_RU.ts \
    app/resource/i18n/app.it_IT.ts \
    app/resource/i18n/app.nl_NL.ts \
    app/resource/i18n/app.pl_PL.ts \
    app/resource/i18n/app.tr_TR.ts \
    app/resource/i18n/app.vi_VN.ts \
    app/resource/i18n/app.th_TH.ts \
    app/resource/i18n/app.id_ID.ts \
    app/resource/i18n/app.hi_IN.ts \
    app/resource/i18n/app.ar_EG.ts \
    app/resource/i18n/app.af_ZA.ts \
    app/resource/i18n/app.am_ET.ts \
    app/resource/i18n/app.az_AZ.ts \
    app/resource/i18n/app.be_BY.ts \
    app/resource/i18n/app.bg_BG.ts \
    app/resource/i18n/app.bn_BD.ts \
    app/resource/i18n/app.bs_BA.ts \
    app/resource/i18n/app.ca_ES.ts \
    app/resource/i18n/app.cs_CZ.ts \
    app/resource/i18n/app.cy_GB.ts \
    app/resource/i18n/app.da_DK.ts \
    app/resource/i18n/app.el_GR.ts \
    app/resource/i18n/app.et_EE.ts \
    app/resource/i18n/app.eu_ES.ts \
    app/resource/i18n/app.fa_IR.ts \
    app/resource/i18n/app.fi_FI.ts \
    app/resource/i18n/app.ga_IE.ts \
    app/resource/i18n/app.gl_ES.ts \
    app/resource/i18n/app.gu_IN.ts \
    app/resource/i18n/app.he_IL.ts \
    app/resource/i18n/app.hr_HR.ts \
    app/resource/i18n/app.hu_HU.ts \
    app/resource/i18n/app.hy_AM.ts \
    app/resource/i18n/app.is_IS.ts \
    app/resource/i18n/app.ka_GE.ts \
    app/resource/i18n/app.kk_KZ.ts \
    app/resource/i18n/app.km_KH.ts \
    app/resource/i18n/app.kn_IN.ts \
    app/resource/i18n/app.lt_LT.ts \
    app/resource/i18n/app.lv_LV.ts \
    app/resource/i18n/app.mk_MK.ts \
    app/resource/i18n/app.ml_IN.ts \
    app/resource/i18n/app.mn_MN.ts \
    app/resource/i18n/app.mr_IN.ts \
    app/resource/i18n/app.ms_MY.ts \
    app/resource/i18n/app.my_MM.ts \
    app/resource/i18n/app.nb_NO.ts \
    app/resource/i18n/app.ne_NP.ts \
    app/resource/i18n/app.nn_NO.ts \
    app/resource/i18n/app.pa_IN.ts \
    app/resource/i18n/app.pt_PT.ts \
    app/resource/i18n/app.ro_RO.ts \
    app/resource/i18n/app.si_LK.ts \
    app/resource/i18n/app.sk_SK.ts \
    app/resource/i18n/app.sl_SI.ts \
    app/resource/i18n/app.sq_AL.ts \
    app/resource/i18n/app.sr_RS.ts \
    app/resource/i18n/app.sv_SE.ts \
    app/resource/i18n/app.sw_KE.ts \
    app/resource/i18n/app.ta_IN.ts \
    app/resource/i18n/app.te_IN.ts \
    app/resource/i18n/app.tg_TJ.ts \
    app/resource/i18n/app.fil_PH.ts \
    app/resource/i18n/app.uk_UA.ts \
    app/resource/i18n/app.ur_PK.ts \
    app/resource/i18n/app.uz_UZ.ts \
    app/resource/i18n/app.zh_HK.ts
